workflows:
  ios_build:
    name: iOS Build Workflow
    max_build_duration: 60  # Optional: Limit the build duration (in minutes)
    scripts:
      - name: Install npm dependencies
        script: |
          npm install -g ionic cordova  # Install Ionic and Cordova globally
          npm install  # Install project-specific npm dependencies

      - name: Build the iOS app
        script: |
          ionic cordova build ios --prod --release  # Build the iOS app in production release mode

    artifacts:
      - build/ios/output/*.ipa  # This specifies where to look for the .ipa file

