workflows:
  ios_build:
    name: iOS Build Workflow
    max_build_duration: 60  # Optional: Limit the build duration (in minutes)
    scripts:
      - name: Install npm dependencies
        script: |
          npm install -g @capacitor/cli  # Install Capacitor globally (if not already installed)
          npm install  # Install project-specific npm dependencies

      - name: Build the iOS app
        script: |
          npx cap open ios  # Build the iOS app in production release mode
          npx cap build ios --prod  # Build the iOS app in production release mode

    artifacts:
      - build/ios/output/*.ipa  # This specifies where to look for the .ipa file

